---
title: "Assignment-1 Graphical Storytelling in R"
author: "Talia Murray and Ivanya Johnson"
date: "2024-08-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Install and load packages
```{r}
library(tidyverse)
```


# Load data set
```{r}
seagrass<-read.csv("../data/SeagrassPubs.csv") # Read in data.
```

# Look at data
```{r}
head(seagrass) # Look at data.
summary(seagrass) # Get summary of data.
glimpse(seagrass) # Look at data
```

# Seperate author and year into 2 variables from Reference
```{r}
# Extract author and year from reference column and create new data frame with these two variables separated.
seagrass1 <- seagrass %>% 
  mutate(Author = str_extract(string = Reference, pattern = "(?<=,\\s).+"),
         PubYear = str_extract(string = Reference, pattern = "[0-9]+")) %>% 
  select(Author:PubYear)
# Combine the Column for publication year to the original data frame using cbind function.
Pubyear = seagrass1$PubYear
seagrass2 <- cbind(seagrass, Pubyear) 
```


# Create Biomass category
```{r}
biomass<-seagrass2 %>% # Create new data frame and select which data frame to pull data from.
  group_by(Pubyear) %>% # Group publications by year.
  select(Pubyear, Seagr.biom.above.dm..g.m..2.) %>% # Select which 2 variables we are interested in using to tally.
   drop_na(Seagr.biom.above.dm..g.m..2.) %>% # Remove na values to only count the years with publications.
    tally() # Use tally function to get information on number of publications.
colnames(biomass) <- c("Pubyear", "tally1") # Create new column names.

biomass1<-seagrass2 %>% # Create new data frame and select which data frame to pull data from.
  group_by(Pubyear) %>%  # Group publications by year.
  select(Pubyear, Seagr.biom.below.dm..g.m..2.) %>% # Select which 2 variables we are interested in using to tally.
  drop_na(Seagr.biom.below.dm..g.m..2.) %>% # Remove na values to only count the years with publications.
    tally() # Use tally function to get information on number of publications.
colnames(biomass1) <- c("Pubyear", "tally2") # Create new column names.

biomass2<-seagrass2 %>% # Create new data frame and select which data frame to pull data from.
  group_by(Pubyear) %>%  # Group publications by year.
  select(Pubyear, Seagr.biom.tot.dm..g.m..2.) %>% # Select which 2 variables we are interested in using to tally.
  drop_na(Seagr.biom.tot.dm..g.m..2.) %>% # Remove na values to only count the years with publications.
    tally() # Use tally function to get information on number of publications.
colnames(biomass2) <- c("Pubyear", "tally3") # Create new column names.


# Organise data into one dataframe.

TBmass1 <- biomass %>%
  full_join(biomass1) # Combine tally columns for biomass and biomass1 into one dataframe.


TBmass2 <- TBmass1 %>%
  full_join(biomass2)  # Combine tally columns for TBmass1 and biomass2 into one dataframe. That puts all three tally columns into one dataframe.



TBmass2$tally1<-as.numeric(TBmass2$tally1) # Make tally1 numeric.
TBmass2$tally2<-as.numeric(TBmass2$tally2) # Make tally2 numeric.
TBmass2$tally3<-as.numeric(TBmass2$tally3) # Make tally3 numeric.

TBmass2[is.na(TBmass2)] <- 0 # Make all NA values equal 0

TBmass2$TotalBiomass<-rowSums(TBmass2[ , c("tally1", "tally2", "tally3")]) # Create new variable TotalBiomass that calculates the sum for each row for each publication year.

```


# Create Structure category
```{r}
Structure1<-seagrass2 %>% # Create new data frame and select which data frame to pull data from.
  group_by(Pubyear) %>% # Group publications by year.
  select(Pubyear, Seagr.cov....) %>% # Select which 2 variables we are interested in using to tally.
   drop_na(Seagr.cov....) %>% # Remove na values to only count the years with publications.
    tally() # Use tally function to get information on number of publications.
colnames(Structure1) <- c("Pubyear", "tally1") # Create new column names.

Structure2<-seagrass2 %>% # Create new data frame and select which data frame to pull data from.
  group_by(Pubyear) %>%  # Group publications by year.
  select(Pubyear, Seagr.shoot.dens....m..2.) %>% # Select which 2 variables we are interested in using to tally.
  drop_na(Seagr.shoot.dens....m..2.) %>% # Remove na values to only count the years with publications.
    tally() # Use tally function to get information on number of publications.
colnames(Structure2) <- c("Pubyear", "tally2") # Create new column names.

Structure3<-seagrass2 %>% # Create new data frame and select which data frame to pull data from.
  group_by(Pubyear) %>%  # Group publications by year.
  select(Pubyear, Seagr.leaf.dens....m..2.) %>% # Select which 2 variables we are interested in using to tally.
  drop_na(Seagr.leaf.dens....m..2.) %>% # Remove na values to only count the years with publications.
    tally() # Use tally function to get information on number of publications.
colnames(Structure3) <- c("Pubyear", "tally3") # Create new column names.



# Organise data into one dataframe.

TStructure1 <- Structure1 %>%
  full_join(Structure2) # Combine tally columns for Structure1 and Structure2 into one dataframe.


TStructure2 <- TStructure1 %>%
  full_join(Structure3)  # Combine tally columns for TStructure1 and Structure3 into one dataframe. That puts all three tally columns into one dataframe.



TStructure2$tally1<-as.numeric(TStructure2$tally1) # Make tally1 numeric.
TStructure2$tally2<-as.numeric(TStructure2$tally2) # Make tally2 numeric.
TStructure2$tally3<-as.numeric(TStructure2$tally3) # Make tally3 numeric.

TStructure2[is.na(TStructure2)] <- 0 # Make all NA values equal 0

TStructure2$TotalStructure<-rowSums(TStructure2[ , c("tally1", "tally2", "tally3")]) # Create new variable TotalBiomass that calculates the sum for each row for each publication year.

```



# Create Production category
```{r}
Production1<-seagrass2 %>% #Create new data frame and select which data frame to pull data from.
  group_by(Pubyear) %>% # Group publications by year.
  select(Pubyear, Seagr.prod.above.dm..g.m..2.day.) %>% # Select which 2 variables we are interested in using to tally.
   drop_na(Seagr.prod.above.dm..g.m..2.day.) %>% # Remove na values to only count the years with publications.
    tally() # Use tally function to get information on number of publications.
colnames(Production1) <- c("Pubyear", "tally1") # Create new column names.

Production2<-seagrass2 %>% #Create new data frame and select which data frame to pull data from.
  group_by(Pubyear) %>%  # Group publications by year.
  select(Pubyear, Seagr.prod.below.dm..g.m..2.day.) %>% # Select which 2 variables we are interested in using to tally.
  drop_na(Seagr.prod.below.dm..g.m..2.day.) %>% # Remove na values to only count the years with publications.
    tally() # Use tally function to get information on number of publications.
colnames(Production2) <- c("Pubyear", "tally2") # Create new column names.

Production3<-seagrass2 %>% #Create new data frame and select which data frame to pull data from.
  group_by(Pubyear) %>%  # Group publications by year.
  select(Pubyear, Seagr.prod.total.dm..g.m..2.day.) %>% # Select which 2 variables we are interested in using to tally.
  drop_na(Seagr.prod.total.dm..g.m..2.day.) %>% # Remove na values to only count the years with publications.
    tally() # Use tally function to get information on number of publications.
colnames(Production3) <- c("Pubyear", "tally3") # Create new column names.




# Organise data into one dataframe.

TProduction1 <- Production1 %>%
  full_join(Production2) # Combine tally columns for Structure1 and Structure2 into one dataframe.


TProduction2 <- TProduction1 %>%
  full_join(Production3)  # Combine tally columns for TStructure1 and Structure3 into one dataframe. That puts all three tally columns into one dataframe.



TProduction2$tally1<-as.numeric(TProduction2$tally1) # Make tally1 numeric.
TProduction2$tally2<-as.numeric(TProduction2$tally2) # Make tally2 numeric.
TProduction2$tally3<-as.numeric(TProduction2$tally3) # Make tally3 numeric.

TProduction2[is.na(TProduction2)] <- 0 # Make all NA values equal 0

TProduction2$TotalProduction<-rowSums(TProduction2[ , c("tally1", "tally2", "tally3")]) # Create new variable TotalBiomass that calculates the sum for each row for each publication year.


```

# Create new data set with all the total values
```{r}
# Join data into new data frame df_new using left join function. Join TBmass2 and Tstructure2 joining using Pubyear.
df_new <- 
  left_join(TBmass2, TStructure2, by = 'Pubyear') %>% 
  mutate(Pubyear = replace_na(Pubyear, 0)) # Replace na values with 0.

# Join data into new data frame df_new2 using left join function. Join df_new and TProduction2 joining using Pubyear.
df_new2 <- 
  left_join(df_new, TProduction2, by = 'Pubyear') %>% 
  mutate(Pubyear = replace_na(Pubyear, 0)) # Replace na values with 0.

summary(df_new2) # Look at new dataframe.


# Remove unwanted variables.
df_new2 <- subset(df_new2, select = -(tally1))
df_new2 <- subset(df_new2, select = -(tally2))
df_new2 <- subset(df_new2, select = -(tally3))
df_new2 <- subset(df_new2, select = -(tally1.x))
df_new2 <- subset(df_new2, select = -(tally1.y))
df_new2 <- subset(df_new2, select = -(tally2.x))
df_new2 <- subset(df_new2, select = -(tally2.y))
df_new2 <- subset(df_new2, select = -(tally3.x))
df_new2 <- subset(df_new2, select = -(tally3.y))

TotalData <- df_new2 # Create new dataframe called TotalData using data in df_new2
TotalData[is.na(TotalData)] <- 0 # Make all NA values equal 0
TotalData <- filter(TotalData, !Pubyear %in% c(2030, 2031, 2032, 2033)) # Remove years 2030, 2031, 2032 and 2033 from Total Data.
TotalData # Look at TotalData.

summary(TotalData) # Get summary of data.

```


# Lengthen data set
```{r}
FinalData <- TotalData |> 
  pivot_longer( # Pivot longer is used to lengthen and reshape dataframe.
    cols = TotalBiomass:TotalProduction, # This line of code is telling which columns need to be reorganised, using the : we tell R that all columns between and including TotalBiomass and TotalProduction are being reshaped.
    names_to = "PublicationType", # This tells R that the reshaped columns will be organised under the new column called PublicationType.
    values_to = "value" # This function tells R that we want to create a new column called value for the data that was stored in the cells of the original columns.
  )
```


# Create Chart Talia
```{r}
ggplot(FinalData, aes(x = Pubyear, y = value, group = PublicationType, linetype = PublicationType, colour = PublicationType)) + # Create mapping aesthetics.
  geom_smooth(se=F) + # Create smooth plot and remove the confidence interval ribbons.
  theme_classic() + # Use classic theme aesthetics.
  labs(
    title = "The Total Number of Seagrass Publications Over Time", # Label title.
    subtitle = "Seagrass research categories inlude biomass, production and structure.", # Create a subtitle.
    x = "Year of Publication", y = "Total Number of Publications", # Create axes labels.
     linetype = "Publication Type", color = "Publication Type",  # Adjust legend title. 
    caption = "Data Sourced From https://doi.org/10.5194/essd-15-511-2023" # Create caption title.
  ) + 
    scale_colour_discrete(labels = c("Biomass", "Production", "Structure")) + # Adjust the labels used for colour legend.
  scale_linetype_discrete(labels = c("Biomass", "Production", "Structure")) + # Adjust the labels used for linetype legend.
  scale_y_continuous(breaks = seq(0, 700, by = 100)) + # Adjust y axis scale.
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) # Change the angle of x axis labels.

#ggsave("Seagrass_plot.pdf") # Save plot as a pdf.

```


# Create Chart Ivy
```{r}
TotalData %>%
  pivot_longer(cols = -Pubyear) %>%
  ggplot(aes(x = Pubyear, y = value, group = name, linetype = name, color = name)) +
  geom_smooth(se=F) + # Create smooth plot and remove the confidence interval ribbons
  theme_classic() +
  labs(
    title = "Number of Seagrass Publications 1975 - 2020",
    subtitle = "Seagrass research categories include biomass, production, and structure",
    caption = "Data Source: https://doi.org/10.5194/essd-15-511-2023",
    x = "Publication Year", y = "Mean Number of Publications",
    linetype = "Publication Type", color = "Publication Type"
  ) +
  scale_color_discrete(labels = c("Biomass", "Production", "Structure")) +
  scale_linetype_discrete(labels = c("Biomass", "Production", "Structure")) +
   scale_y_continuous(breaks = seq(0, 700, by = 100)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggsave("Seagrass_plot_Ivy.jpg") # Save plot as a jpg
```
